config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registration: 'registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :users, only: :show

  resources :links

  root to: 'pages#main'
  get '*short_url', to: 'links#open', as: :shortlink
end

app/views/partials/_links_table.html.erb
<table class="table table-hover fixed-table">
  <thead class="thead-default">
  <tr>
    <th width="18%">Short name</th>
    <th width="59%">Destination</th>
    <th width="8%">Clicks</th>
    <th width="5%"></th>
    <th width="5%"></th>
    <th width="5%"></th>
  </tr>
  </thead>

  <tbody>
  <% links.each do |link| %>
    <tr>
      <td class="hide-overflow"><%= link_to truncate(link.name, length: 40), link %></td>
      <td class="hide-overflow"><%= link_to truncate(link.url, length: 90), link.url %></td>
      <td><%= link.clicks %></td>
      <td class="text-center"><%= link_to(fa_icon('user-circle-o'), link.user) if link.user.present? %></td>
      <td class="text-center"><%= link_to fa_icon('pencil-square-o'), edit_link_path(link) %></td>
      <td class="text-center"><%= link_to fa_icon('trash-o'), link, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/partials/_messages.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-md-6">
      <% flash[:danger] = flash[:alert] if flash[:alert] %>
      <% flash[:info] = flash[:notice] if flash[:notice] %>
      <% flash.delete(:alert) %>
      <% flash.delete(:notice) %>
      <% flash.each do |key, value| %>
        <div class="alert  alert-dismissible fade show alert-<%= key %>" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <%= value %>
        </div>
      <%
        flash.delete(key)
        end %>
    </div>
  </div>
</div>

app/views/partials/_model_errors.html.erb
<% if model.errors.any? %>
  <div class="container">
    <div class="row">
      <div class="col alert alert-dismissible fade show alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
          <strong>Fix <%= pluralize(model.errors.count, 'error') %>:</strong>
          <ul>
          <% model.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-light navbar-toggleable-sm fixed-top bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <span class="navbar-brand">
    <a href="/">bil-game.ru</a> <small>short links you can count on</small>
  </span>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item mr-4">
        <% if policy(Link).create? %>
          <%= link_to 'Create link', new_link_path, class: 'btn btn-outline-danger' %>
        <% end %>
      </li>

      <% if !user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-primary' %>
        </li>
        <li class="nav-item">
          <%= link_to fa_icon('sign-in', text: 'Log in'), new_user_session_path, class: 'btn btn-link' %>
        </li>
    <% else %>
        <li class="nav-item dropdown">
          <%= link_to current_user.email, current_user,
                      class: 'dropdown-toggle btn btn-outline-primary ',
                      id: 'navbarDropdownMenuLink',
                      'data-toggle': 'dropdown',
                      'aria-haspopup': 'true',
                      'aria-expanded': 'false'
          %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to 'My Links', links_path, class: 'dropdown-item' %>
            <%= link_to 'My Profile', current_user, class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to fa_icon('sign-out', text: 'Log out', right: true), destroy_user_session_path, method: 'delete', class: 'dropdown-item' %>
          </div>

        </li>
      <% end %>
    </ul>
  </div>
</nav>